begin;

insert into public.content_versions (content_id, version, content_type, publication_status, review_status, source_category, author, authored_on, effective_from)
values
  ('stage.preparing', 1, 'development_stage', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('stage.settling_in', 1, 'development_stage', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('stage.foundations', 1, 'development_stage', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('stage.exploration', 1, 'development_stage', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('stage.teething', 1, 'development_stage', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('stage.early_adolescence', 1, 'development_stage', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('stage.adolescence', 1, 'development_stage', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('stage.adulthood', 1, 'development_stage', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26');

insert into public.development_stages (content_id, version, stage_key, name, position, approximate_band, focus_areas, description, next_stage_preview, entry_guidance, review_status, effective_from)
values
  ('stage.preparing', 1, 'preparing', 'Preparing for arrival', 1, 'homecoming date in the future', array['Home setup and safety','Supplies','Routine agreement','Choosing a veterinarian','First-night plan'], 'Getting your home and routine ready counts as head start parenting. Everything you sort out now is one less thing to juggle when {name} arrives.', 'Once {name} is home, the first couple of weeks are all about settling in - sleep, routine, and gentle bonding.', '{"kind":"homecoming_future"}', 'pending_professional_review', '2026-07-26'),
  ('stage.settling_in', 1, 'settling_in', 'Settling in', 2, 'first ~2 weeks home', array['Predictable routine','Sleep and crate comfort','Gentle bonding','Name response','Potty rhythm','Low-pressure home exploration'], '{name} is learning that your home is safe and predictable. Routine matters more than training right now - though tiny, fun sessions are a lovely way to bond.', 'Many puppies are ready for a bit more structure after a week or two - short training moments and gentle new experiences.', '{"approx_home_age":"first_2_weeks"}', 'pending_professional_review', '2026-07-26'),
  ('stage.foundations', 1, 'foundations', 'Foundations', 3, '~8-12 weeks', array['Marker and name basics','Short fun training','Handling comfort','Positive early socialization within veterinary guidance','Alone-time foundations'], 'Short, playful practice builds the basics: {name}''s name, a marker word, being handled, and feeling fine alone for a moment. Keep everything easy and rewarding.', 'Around three to four months, many puppies are ready to widen their world - more places, surfaces, and friendly encounters.', '{"age_min_weeks":8,"age_max_weeks":12}', 'pending_professional_review', '2026-07-26'),
  ('stage.exploration', 1, 'exploration', 'Exploration and socialization', 4, '~12-16 weeks', array['Broadening positive exposure','Recall foundations','Leash introduction','Handling and grooming comfort'], 'This is a wonderful window for positive new experiences. One calm, pleasant encounter beats ten rushed ones.', 'Teething often arrives around four months - expect more chewing and plan for it rather than fighting it.', '{"age_min_weeks":12,"age_max_weeks":16}', 'pending_professional_review', '2026-07-26'),
  ('stage.teething', 1, 'teething', 'Teething', 5, '~16-24 weeks', array['Appropriate chew management','Patience with mouthing','Maintaining training momentum','Calm-settle practice'], 'Sore gums mean chewing is a need, not naughtiness. Offer good options, keep sessions short, and keep routines steady.', 'As adolescence approaches, {name} may test boundaries they knew perfectly well. That is normal - consistency wins.', '{"age_min_weeks":16,"age_max_weeks":24}', 'pending_professional_review', '2026-07-26'),
  ('stage.early_adolescence', 1, 'early_adolescence', 'Early adolescence', 6, '~6-9 months', array['Reinforcing recall and leash skills','Impulse-control games','Sustaining socialization quality'], '{name} is getting braver and more independent. Keep recall rewarding, keep practicing in new places, and do not take regressions personally.', 'Full adolescence can bring bigger energy and selective hearing. The habits you keep now carry you through it.', '{"age_min_months":6,"age_max_months":9}', 'pending_professional_review', '2026-07-26'),
  ('stage.adolescence', 1, 'adolescence', 'Adolescence', 7, '~9-18 months', array['Consistency through regression phases','Generalizing skills to new places','Exercise balance'], 'The teenage phase: enthusiasm, energy, and the occasional "who, me?". Stay consistent, keep it rewarding, and this passes.', 'Most dogs settle into adulthood between one and two years - the rhythm you have built becomes your life together.', '{"age_min_months":9,"age_max_months":18}', 'pending_professional_review', '2026-07-26'),
  ('stage.adulthood', 1, 'adulthood', 'Adulthood', 8, '~18 months +', array['Maintenance practice','Enrichment variety','Routine care rhythm'], 'The foundations are laid. Now it is maintenance, enrichment, and enjoying the dog you have raised together.', null, '{"age_min_months":18}', 'pending_professional_review', '2026-07-26');

insert into public.content_versions (content_id, version, content_type, publication_status, review_status, source_category, author, authored_on, effective_from)
values
  ('prep.safe_home', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('prep.supplies', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('prep.vet_choice', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('prep.first_vet_appt', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('prep.sleep_setup', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('prep.routine_agreement', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('prep.records_folder', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('prep.travel_plan', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('prep.name_shortlist', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('prep.first_days_calendar', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('prep.gather_records_questions', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('routine.meals_young_puppy', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('routine.meals_older_puppy', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('routine.meals_adolescent', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('routine.potty_young', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('routine.potty_older', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('routine.sleep', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26');

insert into public.task_definitions (provenance, content_id, content_version, title, category, default_obligation_class, instructions_content_ref, default_effort, default_time_policy, metadata)
values
  ('system', 'prep.safe_home', 1, 'Puppy-proof one room at a time (cords, plants, small objects, cleaners)', 'preparation', 'recommended', '{"content_id":"prep.safe_home","version":1}', 'moderate', 'anytime', '{"timing_window_days_before_homecoming":[14,3]}'),
  ('system', 'prep.supplies', 1, 'Gather starter supplies (crate, bedding, bowls, collar/harness, lead, chews, food per breeder guidance)', 'preparation', 'recommended', '{"content_id":"prep.supplies","version":1}', 'moderate', 'anytime', '{"timing_window_days_before_homecoming":[14,5]}'),
  ('system', 'prep.vet_choice', 1, 'Choose a veterinary practice and save its contact', 'preparation', 'recommended', '{"content_id":"prep.vet_choice","version":1}', 'short', 'anytime', '{"timing_window_days_before_homecoming":[14,7]}'),
  ('system', 'prep.first_vet_appt', 1, 'Book the first veterinary visit', 'preparation', 'recommended', '{"content_id":"prep.first_vet_appt","version":1}', 'short', 'anytime', '{"timing_window_days_before_homecoming":[10,3]}'),
  ('system', 'prep.sleep_setup', 1, 'Choose and set up the first-night sleeping arrangement', 'preparation', 'recommended', '{"content_id":"prep.sleep_setup","version":1}', 'short', 'anytime', '{"timing_window_days_before_homecoming":[10,2]}'),
  ('system', 'prep.routine_agreement', 1, 'Agree the household routine - who does mornings, meals, nights', 'preparation', 'recommended', '{"content_id":"prep.routine_agreement","version":1}', 'short', 'anytime', '{"timing_window_days_before_homecoming":[7,1]}'),
  ('system', 'prep.records_folder', 1, 'Start a folder for breeder/rescue paperwork and health records', 'preparation', 'recommended', '{"content_id":"prep.records_folder","version":1}', 'tiny', 'anytime', '{"timing_window_days_before_homecoming":[7,1]}'),
  ('system', 'prep.travel_plan', 1, 'Plan the journey home (crate/restraint, stops, towels)', 'preparation', 'recommended', '{"content_id":"prep.travel_plan","version":1}', 'short', 'anytime', '{"timing_window_days_before_homecoming":[5,1]}'),
  ('system', 'prep.name_shortlist', 1, 'Settle the name the whole household will use', 'preparation', 'recommended', '{"content_id":"prep.name_shortlist","version":1}', 'tiny', 'anytime', '{"timing_window_days_before_homecoming":"any_time"}'),
  ('system', 'prep.first_days_calendar', 1, 'Keep the first 2-3 days at home low-key - block the calendar', 'preparation', 'recommended', '{"content_id":"prep.first_days_calendar","version":1}', 'tiny', 'anytime', '{"timing_window_days_before_homecoming":[7,1]}'),
  ('system', 'prep.gather_records_questions', 1, 'Gather records and questions', 'preparation', 'recommended', '{"content_id":"prep.gather_records_questions","version":1}', 'short', 'anytime', '{"event_prep_kind":"vet_appointment"}'),
  ('system', 'routine.meals_young_puppy', 1, '3 meals/day in morning, midday, evening windows', 'feeding', 'scheduled', '{"content_id":"routine.meals_young_puppy","version":1}', 'short', 'window', '{"applies_stages":["settling_in","foundations","exploration"],"copy_note":"confirm feeding details with your breeder or veterinarian"}'),
  ('system', 'routine.meals_older_puppy', 1, '3 -> 2 meals/day (household choice)', 'feeding', 'scheduled', '{"content_id":"routine.meals_older_puppy","version":1}', 'short', 'window', '{"applies_stages":["teething","early_adolescence"],"copy_note":"confirm feeding details with your breeder or veterinarian"}'),
  ('system', 'routine.meals_adolescent', 1, '2 meals/day', 'feeding', 'scheduled', '{"content_id":"routine.meals_adolescent","version":1}', 'short', 'window', '{"applies_stages":["adolescence","adulthood"],"copy_note":"confirm feeding details with your breeder or veterinarian"}'),
  ('system', 'routine.potty_young', 1, 'Potty opportunities: after waking, after each meal, after play, before sleep', 'routine', 'scheduled', '{"content_id":"routine.potty_young","version":1}', 'short', 'window', '{"applies_stages":["settling_in","foundations"],"scheduled_as":"window_items_not_exact_times"}'),
  ('system', 'routine.potty_older', 1, 'After waking, after meals, before sleep; reduce as reliability grows', 'routine', 'scheduled', '{"content_id":"routine.potty_older","version":1}', 'short', 'window', '{"applies_stages":["exploration","teething","early_adolescence","adolescence","adulthood"]}'),
  ('system', 'routine.sleep', 1, 'Bedtime wind-down item in the evening window', 'routine', 'scheduled', '{"content_id":"routine.sleep","version":1}', 'short', 'window', '{"applies_stages":["preparing","settling_in","foundations","exploration","teething","early_adolescence","adolescence","adulthood"],"opt_in":true}');

insert into public.content_versions (content_id, version, content_type, publication_status, review_status, source_category, author, authored_on, effective_from)
values
  ('care.brushing', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('care.nail_intro', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('care.tooth_intro', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'),
  ('care.ear_check', 1, 'task_definition', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26');

insert into public.task_definitions (provenance, content_id, content_version, title, category, default_obligation_class, instructions_content_ref, default_effort, default_time_policy, metadata)
values
  ('system', 'care.brushing', 1, 'Brushing session', 'grooming', 'recommended', '{"content_id":"care.brushing","version":1}', 'short', 'anytime', '{"default_cadence":"every_3_days","household_adjustable":true}'),
  ('system', 'care.nail_intro', 1, 'Nail-care habituation (touch, one nail when ready)', 'grooming', 'recommended', '{"content_id":"care.nail_intro","version":1}', 'tiny', 'anytime', '{"default_cadence":"weekly","household_adjustable":true}'),
  ('system', 'care.tooth_intro', 1, 'Tooth-brushing habituation', 'grooming', 'recommended', '{"content_id":"care.tooth_intro","version":1}', 'tiny', 'anytime', '{"default_cadence":"2_3_per_week","household_adjustable":true}'),
  ('system', 'care.ear_check', 1, 'Calm ear look-and-reward', 'grooming', 'recommended', '{"content_id":"care.ear_check","version":1}', 'tiny', 'anytime', '{"default_cadence":"weekly","household_adjustable":true}');

insert into public.content_versions (content_id, version, content_type, publication_status, review_status, source_category, author, authored_on, effective_from)
select content_id, 1, 'training_skill', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'
from (values
  ('skill.marker_intro'), ('skill.name_response'), ('skill.sit'), ('skill.hand_target'), ('skill.recall_foundations'),
  ('skill.leave_it'), ('skill.drop_it'), ('skill.crate_comfort'), ('skill.settle_on_mat'), ('skill.alone_time'),
  ('skill.paw_handling'), ('skill.body_handling'), ('skill.harness_intro'), ('skill.loose_leash'), ('skill.shake')
) as v(content_id);

insert into public.training_skills (content_id, version, skill_group, title, promise, steps, prerequisite_skill_refs, stage_guidance, effort_band, recommended_frequency, common_mistakes, watch_for, going_well, review_status, effective_from)
values
  ('skill.marker_intro', 1, 'Foundations', 'Marker word ("yes!")', 'One little word that tells {name} exactly which moment earned the treat.', '["Pick one short word the whole household will use - yes! works.","Say it once, then hand {name} a treat. Word first, treat after.","Repeat 5-8 times. That is the whole session.","Over the next days, say it the instant {name} does something you like, then treat."]', '{}', 'settling_in', 'tiny', '3-5/week', array['Marking late','Treating before marking'], 'Marking late (the word should catch the exact moment) - reaching for the treat before you have said the word.', '{name}''s ears perk when they hear it - the word now means "that! do that again."', 'pending_professional_review', '2026-07-26'),
  ('skill.name_response', 1, 'Foundations', 'Name response', '{name} hears their name and thinks "something good is about to happen."', '["Wait until {name} is not looking at you.","Say their name once, brightly.","The instant they turn toward you, mark and treat.","If they do not turn, do not repeat the name - make a small fun noise instead, and make it easier next time.","Practice in different rooms, then with mild distractions."]', '{}', 'settling_in', 'tiny', '4-6/week', array['Repeating the name','Using it for scolding'], 'Repeating the name ("Maple. Maple! MAPLE.") teaches that the first call does not count - never use the name for scolding.', 'A quick head-turn on the first call, most of the time, in easy places.', 'pending_professional_review', '2026-07-26'),
  ('skill.sit', 1, 'Foundations', 'Sit', 'A polite default that beats jumping every time.', '["Hold a treat at {name}''s nose, then move it slowly up and slightly back.","As the head comes up, the bottom goes down. The moment it touches - mark and treat.","After a few successes, try the same hand motion without a treat in the hand; treat from the other hand.","Add the word sit just before the motion once the movement is reliable."]', array['skill.marker_intro'], 'foundations', 'tiny', '3-5/week', array['Luring forever','Pushing the rear down'], 'Luring forever (fade the treat from the guiding hand early) - never push the rear down, let {name} figure it out.', '{name} sits on the word or a small hand signal, no treat in sight until after.', 'pending_professional_review', '2026-07-26'),
  ('skill.hand_target', 1, 'Foundations', 'Hand target ("touch")', 'A friendly "come here and check in" that works anywhere.', '["Present a flat palm a hand-width from {name}''s nose.","Puppies are curious - when the nose boops the palm, mark and treat.","Move the palm to new spots: lower, higher, left, right.","Add the word touch just before presenting the hand."]', array['skill.marker_intro'], 'foundations', 'tiny', '3-4/week', array['Moving the hand toward the puppy'], 'Moving your hand toward {name} (let them come to the hand) - sessions longer than a minute or two.', '{name} crosses the room to boop your palm.', 'pending_professional_review', '2026-07-26'),
  ('skill.recall_foundations', 1, 'Recall and safety', 'Recall ("come")', 'The one that matters most: {name} comes when called, happily.', '["Start two steps away in a quiet room. Say {name}, come! once, warmly.","The instant they move toward you, celebrate - mark, treat generously, make it a party.","Release them to go back to whatever they were doing. Coming to you should not end the fun.","Gradually add distance, then new rooms, then the garden.","Sometimes grab the collar gently before treating - so a reach is not scary later."]', array['skill.name_response'], 'foundations', 'short', '3-5/week', array['Calling for unpleasant things','Repeating the cue','Practicing only indoors forever'], 'Calling {name} for things they dislike (baths, ending play) - go and get them instead - repeating the cue - staying at one difficulty forever, or jumping to the park too soon.', 'A fast, happy turn-and-run to you in easy places, every time.', 'pending_professional_review', '2026-07-26'),
  ('skill.leave_it', 1, 'House manners', 'Leave it', '{name} chooses to look away from tempting things - because it pays better.', '["Close a boring treat in your fist and let {name} investigate.","Wait out the licking and pawing. The instant they pull away - mark and treat from the other hand.","Repeat until they pull back from the fist immediately.","Move the closed hand to the floor; same game.","Add the words leave it just before presenting, once the pull-away is quick."]', array['skill.marker_intro'], 'exploration', 'short', '2-4/week', array['Snatching the item away','Escalating too fast'], 'Escalating too fast - an open hand or dropped food is graduate-level. Do not snatch the item away; the point is {name} choosing.', '{name} sees the fist, looks at you instead.', 'pending_professional_review', '2026-07-26'),
  ('skill.drop_it', 1, 'House manners', 'Drop it (trade)', '{name} gives things up willingly, because trading always pays.', '["While {name} holds a toy, offer a treat near their nose.","When the toy drops - mark, treat, and give the toy right back when it is safe to.","Add the words drop it just before the offer.","Practice with different toys; keep the trade generous."]', '{}', 'exploration', 'short', '2-3/week', array['Chasing the puppy','Trading down'], 'Chasing {name} to get the item (that is the best game ever - do not start it) - always trading down (losing the toy forever teaches {name} to guard it).', 'The toy drops on the words, tail still wagging.', 'pending_professional_review', '2026-07-26'),
  ('skill.crate_comfort', 1, 'Calm behavior', 'Crate comfort', 'The crate becomes {name}''s own calm room, not a cage.', '["Set the crate up cozy, door open. Drop treats inside and walk away - no pressure.","Feed meals just inside the door, then further in.","When {name} settles inside on their own, calmly drop a treat in.","Close the door for a few seconds while treating, open before any fuss.","Build duration in small steps, always ending while it is easy."]', '{}', 'settling_in', 'short', 'daily at first', array['Using the crate as punishment','Rushing duration'], 'Using the crate for time-outs - rushing duration (one bad scare undoes a week of good work).', '{name} wanders in for naps with the door open.', 'pending_professional_review', '2026-07-26'),
  ('skill.settle_on_mat', 1, 'Calm behavior', 'Settle on a mat', 'An off-switch: {name} learns that the mat means relax.', '["Put a mat down; treat {name} for any interest in it.","Treat for paws on, then for sitting, then for lying down - at {name}''s pace.","Feed calm: slow, quiet treats between the paws while they are lying down.","Take a step away and return before {name} gets up. Build slowly.","Practice while you sit nearby with a cup of tea - boring is the point."]', array['skill.marker_intro'], 'foundations', 'short', '3-4/week', array['Only practicing when already tired','Expecting long holds early'], 'Only practicing when {name} is already sleepy (fine to start, but practice mildly awake too) - expecting long holds in week one.', '{name} sees the mat come out and flops onto it.', 'pending_professional_review', '2026-07-26'),
  ('skill.alone_time', 1, 'Calm behavior', 'Alone-time foundations', '{name} learns that being alone is safe and short-lived - the foundation against separation stress.', '["Start with {name} settled (mat or crate). Step out of sight for two seconds, return calmly.","Return before any fussing - you are teaching that you always come back and it is fine.","Vary it: sometimes two seconds, sometimes ten. Keep returns boring.","Build toward leaving the room during normal life - kettle on, coat on and off again.","Work up to real short absences only when {name} is relaxed at every step."]', array['skill.crate_comfort'], 'settling_in', 'short', '3-5/week', array['Sneaking out','Jumping to long absences'], 'Sneaking out (let departures be visible and unremarkable) - jumping from one minute to one hour.', '{name} glances up when you leave the room, then goes back to their chew.', 'pending_professional_review', '2026-07-26'),
  ('skill.paw_handling', 1, 'Handling and grooming prep', 'Paw handling', 'Nail trims and muddy-paw wipes without a wrestling match.', '["Touch a paw for one second, mark, treat. That is it.","Progress to holding briefly, then to gently pressing a toe.","Pair every touch with something good; stop before {name} pulls away.","Later, touch paws with a towel, then show the nail clippers nearby - no clipping yet, just good associations."]', '{}', 'settling_in', 'tiny', '3-4/week', array['Gripping tightly','Continuing past discomfort'], 'Gripping tightly when {name} pulls back (release on calm, not on struggle - better yet, go slower) - pushing past discomfort.', '{name} offers a paw and leaves it in your hand.', 'pending_professional_review', '2026-07-26'),
  ('skill.body_handling', 1, 'Handling and grooming prep', 'Ears, mouth, body handling', 'Vet visits and grooming feel like old news, because gentle hands are normal.', '["In a calm moment, touch an ear for a second - mark, treat.","Rotate areas over sessions: ears, lips (lift briefly), collar area, tail, belly.","Keep sessions under two minutes, always ending on an easy touch.","Add gentle restraint last: a soft hold for one second, treat, release."]', array['skill.paw_handling'], 'foundations', 'tiny', '2-4/week', array['Long sessions','Skipping the pairing with rewards'], 'Long sessions - handling without pairing rewards (touch should predict good things, not just happen).', '{name} leans in for the exam-style once-over.', 'pending_professional_review', '2026-07-26'),
  ('skill.harness_intro', 1, 'Leash skills', 'Collar/harness introduction', 'The harness predicts adventures, not restraint.', '["Show the harness; treat {name} for sniffing it.","Feed treats through the head opening so {name} pokes their own head in.","Clip it on loosely for a few seconds while treating, then off.","Build up wearing time during pleasant things - meals, play."]', '{}', 'settling_in', 'tiny', '2-3/week', array['Forcing it on','Leaving it on while distressed'], 'Forcing it over the head - leaving it on while {name} is distressed - take a step back instead.', '{name} sees the harness and comes over.', 'pending_professional_review', '2026-07-26'),
  ('skill.loose_leash', 1, 'Leash skills', 'Loose-leash foundations', 'Walks where the leash stays soft - starting in the hallway, not the high street.', '["Indoors, clip the leash on and just walk around treating {name} for being near your leg.","When the leash goes tight, stop being interesting: stand still. The moment it slackens, mark, treat, walk on.","Change direction often - following you becomes the game.","Take it to the garden, then quiet outdoor spots, keeping sessions short."]', array['skill.harness_intro'], 'exploration', 'short', '3-4/week', array['Letting pulling pay off sometimes','Sessions too long'], 'Letting pulling work sometimes (if tight leash ever gets {name} where they want, pulling pays) - sessions long enough to get frustrating for either of you.', 'Slack-leash steps beside you in easyish places, {name} checking in.', 'pending_professional_review', '2026-07-26'),
  ('skill.shake', 1, 'Fun skills', 'Shake / give paw', 'A party trick that doubles as paw-handling practice.', '["Hold a treat in a loose fist at {name}''s chest height.","Most puppies paw at the fist - the instant a paw lifts, mark and treat.","Add an open palm as the target; treat for a paw landing in it.","Add the word shake just before offering the palm."]', array['skill.paw_handling'], 'exploration', 'tiny', '1-2/week', array['Grabbing the paw instead of shaping'], 'Grabbing the paw instead of letting {name} offer it.', 'Paw in palm on the word - cue applause from the household.', 'pending_professional_review', '2026-07-26');

insert into public.content_versions (content_id, version, content_type, publication_status, review_status, source_category, author, authored_on, effective_from)
select content_id, 1, 'socialization_experience', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'
from (values
  ('soc.people.calm_adult_visitor'), ('soc.people.hat_hood'), ('soc.people.stick_umbrella'), ('soc.people.child_distance'), ('soc.people.delivery_worker_window'),
  ('soc.animals.known_vaccinated_dog'), ('soc.animals.dog_distance'), ('soc.animals.cat_distance'), ('soc.animals.birds_garden'),
  ('soc.sounds.vacuum_low'), ('soc.sounds.doorbell'), ('soc.sounds.hairdryer'), ('soc.sounds.traffic_distance'), ('soc.sounds.thunder_low'), ('soc.sounds.kitchen_clatter'),
  ('soc.surfaces.grass'), ('soc.surfaces.gravel'), ('soc.surfaces.wet_ground'), ('soc.surfaces.smooth_floor'), ('soc.surfaces.wobbly_cushion'), ('soc.surfaces.low_step'),
  ('soc.environments.front_garden'), ('soc.environments.quiet_street_carried'), ('soc.environments.car_park_distance'), ('soc.environments.friends_home'), ('soc.environments.outdoor_cafe_distance'),
  ('soc.handling.towel_wipe'), ('soc.handling.brush_touch'), ('soc.handling.nail_clipper_shown'), ('soc.handling.gently_held'), ('soc.handling.harness_on_off'),
  ('soc.transportation.stationary_car'), ('soc.transportation.short_car_ride'), ('soc.transportation.crate_in_car'),
  ('soc.household_objects.umbrella_opening'), ('soc.household_objects.bin_bag_rustle'), ('soc.household_objects.broom'), ('soc.household_objects.suitcase_wheels'), ('soc.household_objects.mirror')
) as v(content_id);

insert into public.socialization_catalog (content_id, version, category, experience_key, label, caution_text, response_vocabulary, review_status, effective_from)
values
  ('soc.people.calm_adult_visitor', 1, 'People', 'calm_adult_visitor', 'Calm adult visitor', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.people.hat_hood', 1, 'People', 'hat_hood', 'Person with a hat/hood', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.people.stick_umbrella', 1, 'People', 'stick_umbrella', 'Person with a stick or umbrella', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.people.child_distance', 1, 'People', 'child_distance', 'Child at a distance', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.people.delivery_worker_window', 1, 'People', 'delivery_worker_window', 'Delivery worker observed from window', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.animals.known_vaccinated_dog', 1, 'Animals', 'known_vaccinated_dog', 'Calm vaccinated adult dog (known)', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.animals.dog_distance', 1, 'Animals', 'dog_distance', 'Dog seen at a distance', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.animals.cat_distance', 1, 'Animals', 'cat_distance', 'Cat at a distance', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.animals.birds_garden', 1, 'Animals', 'birds_garden', 'Birds in the garden', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.sounds.vacuum_low', 1, 'Sounds', 'vacuum_low', 'Vacuum at low volume/distance', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.sounds.doorbell', 1, 'Sounds', 'doorbell', 'Doorbell', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.sounds.hairdryer', 1, 'Sounds', 'hairdryer', 'Hairdryer', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.sounds.traffic_distance', 1, 'Sounds', 'traffic_distance', 'Traffic from a distance', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.sounds.thunder_low', 1, 'Sounds', 'thunder_low', 'Recorded thunder at low volume', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.sounds.kitchen_clatter', 1, 'Sounds', 'kitchen_clatter', 'Kitchen clatter', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.surfaces.grass', 1, 'Surfaces', 'grass', 'Grass', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.surfaces.gravel', 1, 'Surfaces', 'gravel', 'Gravel', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.surfaces.wet_ground', 1, 'Surfaces', 'wet_ground', 'Wet ground', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.surfaces.smooth_floor', 1, 'Surfaces', 'smooth_floor', 'Smooth floor', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.surfaces.wobbly_cushion', 1, 'Surfaces', 'wobbly_cushion', 'Wobbly cushion', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.surfaces.low_step', 1, 'Surfaces', 'low_step', 'Low step', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.environments.front_garden', 1, 'Environments', 'front_garden', 'Front garden', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.environments.quiet_street_carried', 1, 'Environments', 'quiet_street_carried', 'Quiet street (carried if pre-vaccination per vet guidance)', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.environments.car_park_distance', 1, 'Environments', 'car_park_distance', 'Car park at a distance', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.environments.friends_home', 1, 'Environments', 'friends_home', 'Friend''s home', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.environments.outdoor_cafe_distance', 1, 'Environments', 'outdoor_cafe_distance', 'Outdoor cafe from a distance', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.handling.towel_wipe', 1, 'Handling', 'towel_wipe', 'Towel wipe-down', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.handling.brush_touch', 1, 'Handling', 'brush_touch', 'Brush touch', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.handling.nail_clipper_shown', 1, 'Handling', 'nail_clipper_shown', 'Nail-clipper shown and touched', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.handling.gently_held', 1, 'Handling', 'gently_held', 'Being gently held', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.handling.harness_on_off', 1, 'Handling', 'harness_on_off', 'Harness on/off', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.transportation.stationary_car', 1, 'Transportation', 'stationary_car', 'Stationary car with treats', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.transportation.short_car_ride', 1, 'Transportation', 'short_car_ride', 'Short car ride', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.transportation.crate_in_car', 1, 'Transportation', 'crate_in_car', 'Crate in the car', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.household_objects.umbrella_opening', 1, 'Household objects', 'umbrella_opening', 'Umbrella opening', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.household_objects.bin_bag_rustle', 1, 'Household objects', 'bin_bag_rustle', 'Bin bag rustle', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.household_objects.broom', 1, 'Household objects', 'broom', 'Broom', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.household_objects.suitcase_wheels', 1, 'Household objects', 'suitcase_wheels', 'Suitcase with wheels', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26'),
  ('soc.household_objects.mirror', 1, 'Household objects', 'mirror', 'Mirror', 'Ask your vet where {name} can go before their vaccinations are complete. Watching from a distance and being carried both count as great socialization.', array['relaxed','curious','neutral','hesitant','fearful'], 'pending_professional_review', '2026-07-26');

insert into public.content_versions (content_id, version, content_type, publication_status, review_status, source_category, author, authored_on, effective_from)
select content_id, 1, 'recommendation_rule', 'published', 'pending_professional_review', 'product_seed', 'PetCompanion product seed', '2026-07-26', '2026-07-26'
from (values
  ('rule.prep_window'), ('rule.active_skill_practice'), ('rule.start_next_skill'), ('rule.socialization_breadth'), ('rule.handling_cadence'),
  ('rule.brushing'), ('rule.alone_time'), ('rule.growth_photo'), ('rule.event_prep_vet'), ('rule.homecoming_routine')
) as v(content_id);

insert into public.recommendation_rules (content_id, version, name, description, category, eligibility, cooldown_days, frequency_cap, effort_band, default_time_window, default_priority, explanation_template, review_status, effective_from)
values
  ('rule.prep_window', 1, 'Preparation window', 'Selects prep.* items by their timing windows.', 'preparation', '{"selects":"prep.*","stage":["preparing"],"days_to_homecoming":"within_item_window"}', 0, '{"each_item":"once"}', 'short', 'anytime', 'P3', '{Puppy} comes home in {n} days.', 'pending_professional_review', '2026-07-26'),
  ('rule.active_skill_practice', 1, 'Active skill practice', 'Selects a session for an active TrainingGoal.', 'training', '{"goal_status":"active","not_paused":true}', 1, '{"per_skill":"skill_frequency_per_week"}', 'short', 'anytime', 'P3', '{Skill} is an active goal - last practiced {n} days ago.', 'pending_professional_review', '2026-07-26'),
  ('rule.start_next_skill', 1, 'Start next skill', 'Starts an eligible not-started skill.', 'training', '{"active_goal_count_lt":2,"prereqs":"met","stage":"matches"}', 3, null, 'tiny', 'anytime', 'P3', '{Puppy}''s {stage} stage is a good time to begin {skill}.', 'pending_professional_review', '2026-07-26'),
  ('rule.socialization_breadth', 1, 'Socialization breadth', 'Selects an experience from the least-recently-visited category.', 'socialization', '{"stages":["settling_in","foundations","exploration","teething","early_adolescence"],"category_not_excluded":true}', 2, '{"per_category_min_gap_days":2}', 'short', 'anytime', 'P3', '{Puppy} has not explored {category} recently - one calm, positive experience is plenty.', 'pending_professional_review', '2026-07-26'),
  ('rule.handling_cadence', 1, 'Handling cadence', 'Selects paw/body handling practice.', 'training', '{"stage_from":"settling_in","skill_not_paused":true}', 2, null, 'tiny', 'anytime', 'P3', 'Short, pleasant handling now makes grooming and vet visits easier later.', 'pending_professional_review', '2026-07-26'),
  ('rule.brushing', 1, 'Brushing', 'Selects a brushing session.', 'grooming', '{"stage_from":"settling_in","household_adjustable":true}', 3, null, 'tiny', 'anytime', 'P3', 'A brief brushing session keeps {Puppy} comfortable with grooming.', 'pending_professional_review', '2026-07-26'),
  ('rule.alone_time', 1, 'Alone-time practice', 'Selects alone-time practice.', 'training', '{"goal_active_or_stage_lte":"foundations"}', 2, null, 'short', 'anytime', 'P3', 'Short, easy departures now help {Puppy} feel fine alone later.', 'pending_professional_review', '2026-07-26'),
  ('rule.growth_photo', 1, 'Weekly growth photo', 'Selects an opt-in weekly growth photo.', 'life', '{"opt_in":true,"p2":true}', 7, null, 'tiny', 'anytime', 'P4', 'It has been a week - a quick photo keeps {Puppy}''s growth story going.', 'pending_professional_review', '2026-07-26'),
  ('rule.event_prep_vet', 1, 'Vet event preparation', 'Selects Gather records and questions before a vet appointment.', 'preparation', '{"event_kind":"vet_appointment","within_days":3}', 0, '{"each_event":"once"}', 'short', 'anytime', 'P2', '{Puppy}''s appointment is {when} - having records and questions ready helps.', 'pending_professional_review', '2026-07-26'),
  ('rule.homecoming_routine', 1, 'Homecoming routine', 'Selects routine confirmation when homecoming is today or tomorrow.', 'routine', '{"homecoming":"today_or_tomorrow"}', 0, '{"per_pet":"once"}', 'short', 'anytime', 'P3', '{Puppy} is almost home - a shared routine makes the first week calmer.', 'pending_professional_review', '2026-07-26');

commit;
